### PR TITLE
multitargeting with core

### PR DESCRIPTION
**Pull request by virzak**
You'll need the latest daily build for dotnet core 3

Bulid using `dotnet build`
Run the demo with `dotnet run --framework net45` or `dotnet run --framework netcoreapp3.0`

Original library targets 4.0, but there is an [issue](https://github.com/dotnet/core/issues/2085#issuecomment-453310547) with that right now. Hopefully gets resolved soon, through library update or a workaround.

This issue can be addressed after the merge https://github.com/Dirkster99/InplaceEditBoxLib/issues/4

Update: updated the library to target 4.0 using the workaround, so there is 0 impact on end-users

Update 2: Packing should be super easy `dotnet pack -c Release`. All package info is in the csproj file.

### CODE REVIEW

**Comment by Dirkster99** [comment]
Hi Victor,

thanks for the input. I have merged this into a separate branch called NetCoreMultiTargeting since master seems to be to early right now. I need to lookup and process your description to really understand the consequences of this change. To speed me up - would you be able to give me a step by step description of what I should do to verify how the new version from the pull request should work? I am looking for something like this:

- download and install .NetCore daily build from here (link and version for Windows 10?)
- Open the NetCoreMultiTargeting branch in VS
   or use cmd to issue command xyz on source from the branch ???
- Select Option X,Y,Z and Start ...

This would be really helpful as I would otherwise have to research this and I just do not have that much experience with dotnet yet ...thanks

**Comment by virzak** [comment]
The most important thing about this change is that the consequences are minimal for consumers of this library. They are not different from any other update. The code is unchanged and .net framework assembly is the same as before. This is an addition of .net core target framework.

Minimum requirements:
- Download the [daily build](https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries) of .net core 3.0 SDK
- Run `dotnet pack -c Release` in the UserNotifications\source\UserNotification directory. This will build and package a pre-release version.
- Deploy nupkg to Nuget (public, private, or a local folder). It will be a pre-release version
- In a consuming project (InplaceEditBoxLib or other) enable "prerelease" and download the newly deployed version of the package.
  - In case of InplaceEditBoxLib it is important to run `CleanAll.bat` and ensure all projects are updated to the same version of UserNotification.
- Rebuild the solution and run a demo (InPlaceEditBoxDemo or other) to ensure the upgrade hasn't broken anything.

More details:
- The new branch can be build with `dotnet build`
- The demo project (also multitargeted) can be run with either framework, which needs to be specified.
  - In VS 2019 you can select the framework using UI 
image
  - You can run using `dotnet run --framework net45` or `dotnet run --framework netcoreapp3.0` from command line

**Comment by Dirkster99** [comment]
Thanks for the detailed explanation. I'll try to get through this ASAP - not sure when exactly but I should be able to have the preview nuget by Friday evenning'ish or so - I'll get back to you ASAP, thanks

**Comment by Dirkster99** [comment]
I am not really able to spend much time on it today but I managed to execute the first steps towards installing the Net Core 3.0 bits and compilling the project - it works a prescribed :-) only problem I found is the transparanet background #2 which I remember having seen before but do not remember the cause - so I'll be looking into this tomorrow and hopefully be finding the source of the problem

- more likely then not the application isn't loading the styles in App.xaml? or something like this - I'll be in touch, cheers.

**Comment by virzak** [comment]
@Dirkster99 Thanks, I'll look into this too if I get a chance

**Pull request merged**
